# Generated by Django 5.2.7 on 2025-11-26 14:54

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0005_aimodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodel",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
