# Generated by Django 5.2.7 on 2025-12-04 11:02

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0006_applicationconfiguration_vlm_analysis_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodel",
            name="supplier",
            field=models.CharField(
                choices=[
                    ("alibaba_cloud_bailian", "Alibaba Cloud Bailian"),
                    ("deepseek", "DeepSeek"),
                    ("openai", "OpenAI"),
                    ("kimi", "Kimi"),
                    ("volcano_engine", "Volcano Engine"),
                    ("generic_openai", "Generic OpenAI"),
                ],
                max_length=64,
                verbose_name="supplier",
            ),
        ),
    ]
