# Generated by Django 5.2.7 on 2025-12-04 13:14

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("paperless", "0009_init_prompts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
